services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=task
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8003 talks_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=task
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
