name: Django CI with Coverage and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install coverage and setup Docker Compose
        run: |
          pip install coverage
          docker-compose --version

      - name: Build Docker images
        run: docker-compose build

      - name: Run Django tests with coverage
        run: |
          docker-compose run --rm web coverage run manage.py test
          docker-compose run --rm web coverage report

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Start services (compose up)
        run: docker-compose up -d
