name: Django CI with Coverage and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker compose -f talks_project/docker-compose.yml build  # Correct path to docker-compose.yml

      - name: Run Django tests with coverage
        run: |
          docker compose -f talks_project/docker-compose.yml run --rm web coverage run manage.py test
          docker compose -f talks_project/docker-compose.yml run --rm web coverage report

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker compose -f talks_project/docker-compose.yml build  # Correct path to docker-compose.yml

      - name: Start services (docker compose up)
        run: docker compose -f talks_project/docker-compose.yml up
